// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV2k7uo9sqdkiA1jTQlosHjuHsLqyEnUA',
    appId: '1:510130253782:web:85dd219a27fc834a943e77',
    messagingSenderId: '510130253782',
    projectId: 'distribuicao-alimentos',
    authDomain: 'distribuicao-alimentos.firebaseapp.com',
    databaseURL: 'https://distribuicao-alimentos-default-rtdb.firebaseio.com',
    storageBucket: 'distribuicao-alimentos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHxPj3gnP-krT0tKUvHhLYPefm7C7ytiE',
    appId: '1:510130253782:android:5d3e6c0e90ff5c33943e77',
    messagingSenderId: '510130253782',
    projectId: 'distribuicao-alimentos',
    databaseURL: 'https://distribuicao-alimentos-default-rtdb.firebaseio.com',
    storageBucket: 'distribuicao-alimentos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_27fW6FICHSptn_2b2Y7UH9L3vU-JTEg',
    appId: '1:510130253782:ios:9a893823249cf8af943e77',
    messagingSenderId: '510130253782',
    projectId: 'distribuicao-alimentos',
    databaseURL: 'https://distribuicao-alimentos-default-rtdb.firebaseio.com',
    storageBucket: 'distribuicao-alimentos.appspot.com',
    iosClientId:
        '510130253782-huo953cl6djt3677fsv02aqb4ab95ip5.apps.googleusercontent.com',
    iosBundleId: 'com.example.importFoods',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_27fW6FICHSptn_2b2Y7UH9L3vU-JTEg',
    appId: '1:510130253782:ios:9a893823249cf8af943e77',
    messagingSenderId: '510130253782',
    projectId: 'distribuicao-alimentos',
    databaseURL: 'https://distribuicao-alimentos-default-rtdb.firebaseio.com',
    storageBucket: 'distribuicao-alimentos.appspot.com',
    iosClientId:
        '510130253782-huo953cl6djt3677fsv02aqb4ab95ip5.apps.googleusercontent.com',
    iosBundleId: 'com.example.importFoods',
  );
}
